### ISSUE TITLE
The application crashes when accessing the Rate/Vote giver list 

### ISSUE THREAD

**Issue by ahyar92** [hapramp/Hapramp-Android#281]
### Expected behavior
I should be able to access the Rate / Vote grantor list feature without experiencing a crash

### Actual behavior
When I try to see the list of Giver Rate / Vote in one of the posts, suddenly the application crashes and exits by itself.

### How to reproduce
1. Install and open the application
2. Login
3. Next, go to the Feed page
4. And click on the Giver Rate / Vote list in one of the posts.
![t3t3t](https://user-images.githubusercontent.com/37846899/53695143-6d7c1200-3dea-11e9-85bd-6f5539e51a74.jpg)

*Then you will find problems like mine.*

### Recording Of The Bug

https://youtu.be/634G_WfetDo

### Logcat
```
03-03 19:08:25.900 21983 21983 E AndroidRuntime: FATAL EXCEPTION: main
03-03 19:08:25.900 21983 21983 E AndroidRuntime: Process: com.hapramp, PID: 21983
03-03 19:08:25.900 21983 21983 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hapramp/com.hapramp.ui.activity.VotersListActivity}: java.lang.NumberFormatException: Invalid double: "0,002"
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: Caused by: java.lang.NumberFormatException: Invalid double: "0,002"
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at java.lang.StringToReal.initialParse(StringToReal.java:164)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at java.lang.StringToReal.parseDouble(StringToReal.java:282)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:301)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at com.hapramp.ui.activity.VotersListActivity.a(Unknown Source)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at com.hapramp.ui.activity.VotersListActivity.m(Unknown Source)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at com.hapramp.ui.activity.VotersListActivity.onCreate(Unknown Source)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6303)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
03-03 19:08:25.900 21983 21983 E AndroidRuntime: 	... 9 more
```

----
### Environment
Tested on 2 devices:

<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>Xiaomi Redmi 4X</td><td>Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)</td>
<tr><td>Xiaomi Redmi Note 4</td><td>Marshmallow, 6.0 mRA58K (DECA-CORE MAX 2,11GHz, RAM: 3 gb)</td>

**Comment by bxute** [comment]
@ahyar92 
Thanks for reporting the issue.
We regret the inconvenience.

FYI, let me clarify the reason.
App assumes all the vote values to be in `x.xxxx` (Dot is used) Format.
But the data received was in `x,xxx` (Comma is used) Format.

This issue will be with only few posts.
We will resolve the issue in the very next update. 😊

**Comment by ahyar92** [comment]
Nice to help you guys :)

**Comment by bxute** [comment]
@ahyar92 
Since this is an issue due to the locale of the user, we would request you to verify whether the issue persists in the new apk with a patch or not.

Find the apk at: https://drive.google.com/file/d/11Wlzzyqd9P-p5AertNDTw6RKhG7wMFF-/view?usp=sharing

**Comment by ahyar92** [comment]
@bxute Hi, the problem has been solved :)
By the way, after I searched further, it turned out that the crash only happened if my smartphone was in a language other than English. When I change the settings of my smartphone into English, everything is fine.
